/* eslint-disable @next/next/no-page-custom-font */
import React from "react";
import Head from "next/head";

const Layout = ({ children }: React.PropsWithChildren<{}>) => (
  <div>
    <Head>
      <title>How Long To Binge</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
        rel="stylesheet"
      />
    </Head>
    <main>{children}</main>
  </div>
);

export default Layout;
